name: Send mail
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  send:
    name: Send mail
    runs-on: ubuntu-latest
    steps:
      - name: make file
        run: touch test.txt
      - name: write file
        run: echo "this is test file" > text.txt
      - name: send mail
        uses: AlexisMateo/sendmail-action@5
        with:
          smtp-server: smtp.gmail.com
          smtp-server-port: 465
          auth-user: ${{secrets.MAIL_USERNAME}}
          auth-password: ${{secrets.MAIL_PASSWORD}}
          title: Send File by Email test
          body: Build job of ${{github.repository}} completed successfully!
          to: ${{secrets.TO_LIST}}
          from: Bot
          is-tls: false
          commit-message: true
          
    
