name: Check Env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  setupenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check env
      - with:
          script: |
            TAG=$(git tag)
      - run:
          echo 'TAG = ${TAG}'
          
