name: Check Env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  setupenv:
    runs-on: ubuntu-latest
    outputs:
      lasttag: ${{ steps.setting.outputs.lasttag }}
    steps:
      - name: checkout repo
      - uses: actions/checkout@v2
      - name: check env
        id: setting
        run: |
          echo "::set-output name=lasttag::$(echo 'this is last value')"        
#          echo "::set-output name=last::$(git tag --sort=-version:refname | head -n 1 )"
  after:
    runs-on: ubuntu-latest
    needs: setupenv
    steps:
      - name: check result
        run: echo ${{needs.setupenv.outputs.lasttag}}
#       - name: check result2
#         run: echo ${{needs.setupenv.outputs.last}}
