name: Check Env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  setupenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo version is $(git version)
      - run: echo status is $(git status)
      - run: echo tag is $(git tag)
          
