name: Check Env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check env
        env:
          GITVAL: ${{toJson(github) }}
        run: echo "$GITVAL"
